[package]
name = "builder_core"
version = "0.0.0"
authors = ["The Habitat Maintainers <humans@habitat.sh>"]
workspace = "../../"
edition = "2018"

[dependencies]
base64 = "*"
bitflags = "*"
chrono = { version = "*", features = ["serde"] }
clippy = { version = "*", optional = true }
dogstatsd = "*"
env_proxy = "*"
glob = "*"
habitat-builder-protocol = { path = "../builder-protocol" }
lazy_static = "*"
libarchive = "*"
log = "*"
petgraph = "*"
protobuf = "*"
rand = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
time = "*"
toml = { version = "*", default-features = false }
walkdir = "*"
reqwest = "=0.9.17"
url = "*"
zmq = { git = "https://github.com/habitat-sh/rust-zmq", branch = "release/v0.8" }

[dependencies.habitat_core]
git = "https://github.com/habitat-sh/habitat.git"
